Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 99

AllCops:
  TargetRubyVersion: 2.4.1

Metrics/BlockLength:
 Exclude:
   - 'spec/**/*.rb'

Documentation:
 Enabled: false

Style/StringLiterals:
 Enabled: false

Style/StringLiteralsInInterpolation:
 Enabled: false

Layout/IndentationConsistency:
 EnforcedStyle: normal

AllCops:
  Exclude:
    - './texttest_fixture.rb'
    - './lib/item.rb'
